"use client";
import "./bank-cashflow.css";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import TransactionDetail from "./transaction-detail";
import type { MovementRecord } from "./movement-dialog";
import { formatHebrewDate } from "./hebrew-date";
import { todayInIsrael, type FinancePeriod } from "./settlement";
import { clearSettlementCache, loadSettlements } from "./settlement-client";

const periods:{key:FinancePeriod;label:string}[]=[{key:"month",label:"חודשי"},{key:"year",label:"שנתי"},{key:"all",label:"כל הזמנים"}];
const query=(period:FinancePeriod,anchor:string,currency="ILS",summaryOnly=false)=>`period=${period}&month=${anchor.slice(0,7)}&currency=${currency}${summaryOnly?"&summaryOnly=1":""}`;
export function BankSummary(){
 const anchor=todayInIsrael(),[period,setPeriod]=useState<FinancePeriod>("all"),[data,setData]=useState<any>(null),[error,setError]=useState(false);
 useEffect(()=>{let active=true;setError(false);const load=(fresh=false)=>loadSettlements(query(period,anchor,"ILS",true),fresh).then(d=>active&&setData(d.summary)).catch(()=>active&&setError(true));void load();const reload=()=>{clearSettlementCache();void load(true)};window.addEventListener("settlement-updated",reload);return()=>{active=false;window.removeEventListener("settlement-updated",reload)}},[period,anchor]);
 const money=(n:number)=>Number(n||0).toLocaleString("he-IL",{style:"currency",currency:"ILS"});
 const range=period==="month"?"החודש":period==="year"?"השנה":"כל הזמנים";
 return <section className="bank-overview"><div className="finance-period-tabs" aria-label="טווח סיכום כספי">{periods.map(item=><button key={item.key} className={period===item.key?"active":""} onClick={()=>setPeriod(item.key)}>{item.label}</button>)}</div><div className="bank-summary bank-summary-primary"><article className="donation-total-card"><small>סך התרומות {range}</small>{!data&&!error?<i className="amount-skeleton"/>:<div className="donation-total-values"><span><em>לאחר עמלות</em><strong>{error?"לא זמין":money(data.net)}</strong></span><span><em>ברוטו</em><b>{error?"—":money(data.gross)}</b></span></div>}<small>כל התרומות שבוצעו בתקופה שנבחרה</small></article>{[["actual","מתוך זה כבר נכנס לחשבון"],["pending","מתוך זה צפוי להיכנס"]].map(([key,label])=><article key={key}><small>{label}</small>{!data&&!error?<i className="amount-skeleton"/>:<strong>{error?"לא זמין":money(data[key])}</strong>}<small>נטו לאחר עמלות</small></article>)}</div></section>
}
export default function BankCashflow(){
 const[month,setMonth]=useState(()=>todayInIsrael().slice(0,7)),[currency,setCurrency]=useState("ILS"),[data,setData]=useState<any>(null),[error,setError]=useState(""),[day,setDay]=useState(""),[selected,setSelected]=useState<MovementRecord|null>(null);
 useEffect(()=>{let active=true;setError("");setDay("");loadSettlements(query("month",month,currency)).then(d=>active&&setData(d)).catch(()=>active&&setError("לא ניתן לטעון את התזרים. נסה שוב."));const reload=()=>{clearSettlementCache();void loadSettlements(query("month",month,currency),true).then(d=>active&&setData(d))};window.addEventListener("settlement-updated",reload);return()=>{active=false;window.removeEventListener("settlement-updated",reload)}},[month,currency]);
 const money=(n:number)=>Number(n||0).toLocaleString("he-IL",{style:"currency",currency}),rows:any[]=data?.transactions||[],net=(r:any)=>Math.round((r.amount-(r.feeAmount||0))*100)/100;
 const activeDays=useMemo(()=>{const dates=new Set<string>();for(const row of rows){if(row.settlement.expected?.startsWith(month))dates.add(row.settlement.expected);if(row.settlement.actual?.startsWith(month))dates.add(row.settlement.actual)}return [...dates].sort()},[rows,month]);
 const rowsForDay=(date:string)=>rows.filter(r=>date==="unplanned"?!r.settlement.expected&&!r.settlement.actual:r.settlement.expected===date||r.settlement.actual===date);
 return <div className="bank-stack"><h2>זיכויים ותזרים בנקאי</h2><p>הכסף מחושב כנכנס במועד שהוגדר לאמצעי התשלום. תנועה שסומנה כחריגה ממתינה לבדיקה.</p><div className="bank-rule"><label>חודש<input aria-label="חודש תזרים" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label><label>מטבע<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="ILS">שקל</option><option value="USD">דולר</option><option value="EUR">אירו</option></select></label></div>{error&&<p role="alert">{error}</p>}{!data&&!error&&<div className="cashflow-skeleton" aria-label="טעינת נתוני תזרים"><i/><i/><i/></div>}{data&&<><section className="bank-summary">{[["planned","סה״כ צפוי בחודש"],["actual","נכנס לחשבון"],["pending","עדיין ממתין"],["overdue","חריגות באיחור"]].map(([k,label])=><article key={k}><small>{label}</small><strong>{money(data.summary[k])}</strong></article>)}</section>{activeDays.length?<div className="bank-days">{activeDays.map(date=>{const dateRows=rowsForDay(date),amount=dateRows.reduce((s,r)=>s+net(r),0),entered=dateRows.every(r=>!!r.settlement.actual);return <button key={date} className={day===date?"selected":""} onClick={()=>setDay(date)}><b>{date.slice(8)}.{date.slice(5,7)}</b><small>{formatHebrewDate(date)}</small><span>{money(amount)}</span><small>{entered?"נכנס לחשבון":"צפוי להיכנס"}</small></button>})}</div>:<div className="bank-empty">אין בחודש זה מועדי זיכוי עם סכום.</div>}{data.summary.unplanned>0&&<Button variant="outline" onClick={()=>setDay("unplanned")}>ללא מועד זיכוי: {money(data.summary.unplanned)}</Button>}{day&&<section className="config-panel bank-stack"><h3>{day==="unplanned"?"דורש הגדרת מועד זיכוי":`${day} · ${formatHebrewDate(day)}`}</h3>{rowsForDay(day).map(r=><Button variant="outline" className="bank-transaction" key={r.id} onClick={()=>setSelected(r)}>{r.donorName} · {money(net(r))} · {r.paymentMethod} · {r.settlement.status}</Button>)}</section>}<p className="bank-footnote">הסכומים נטו לאחר עמלה. תרומה וזיכוי הם אותה תנועה ואינם נספרים פעמיים.</p></>}<TransactionDetail transaction={selected} onOpenChange={v=>!v&&setSelected(null)}/></div>
}
