"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Landmark, RotateCcw, Save, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { todayInIsrael } from "./settlement";
type Row={id:number;date:string;expectedBalance:number;actualBalance:number;difference:number;matched:boolean};
type Data={expectedBalance:number;baseline:{date:string;balance:number}|null;history:Row[]};
const money=(n:number)=>Number(n||0).toLocaleString("he-IL",{style:"currency",currency:"ILS"});
export default function BankReconciliation(){
 const[date,setDate]=useState(todayInIsrael()),[data,setData]=useState<Data|null>(null),[actual,setActual]=useState(""),[note,setNote]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch(`/api/bank-reconciliation?date=${date}&currency=ILS`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)};
 useEffect(()=>{setNotice("");void load().catch(()=>setNotice("לא ניתן לחשב את היתרה כרגע"))},[date]);
 const difference=actual===""?null:Math.round((Number(actual)-Number(data?.expectedBalance||0))*100)/100;
 async function save(){setBusy(true);setNotice("");try{const r=await fetch("/api/bank-reconciliation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,currency:"ILS",actualBalance:actual,note})}),j=await r.json();if(!r.ok)throw new Error(j.error);setNotice(j.reconciliation.matched?"היתרה תואמת ונשמרה":"הבדיקה נשמרה עם הפרש שדורש בירור");setActual("");setNote("");await load()}catch(e){setNotice(e instanceof Error?e.message:"השמירה נכשלה")}finally{setBusy(false)}}
 async function recordReturn(){if(!confirm("לרשום עמלת החזרת הוראת קבע בנקאית לפי התעריף שבהגדרות?"))return;setBusy(true);try{const r=await fetch("/api/bank-reconciliation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"return_fee",date,currency:"ILS",note})}),j=await r.json();if(!r.ok)throw new Error(j.error);setNotice(`נרשמה עמלת החזרה בסך ${money(j.fee)}`);window.dispatchEvent(new Event("settlement-updated"));await load()}catch(e){setNotice(e instanceof Error?e.message:"הרישום נכשל")}finally{setBusy(false)}}
 return <section className="bank-reconciliation config-panel"><div className="panel-head"><div><h3><Landmark/> התאמת יתרה מול הבנק</h3><p>בדיקה יומית שהיתרה המחושבת במערכת תואמת ליתרה בחשבון.</p></div></div><div className="reconciliation-grid"><label>תאריך בדיקה<input type="date" max={todayInIsrael()} value={date} onChange={e=>setDate(e.target.value)}/></label><article><small>יתרה צפויה במערכת</small><strong>{data?money(data.expectedBalance):"מחשב..."}</strong><em>{data?.baseline?`מהבדיקה האחרונה ב־${data.baseline.date}`:"בדיקה ראשונה — היתרה תהפוך לנקודת הפתיחה"}</em></article><label>יתרה בפועל בבנק<input inputMode="decimal" type="number" step="0.01" value={actual} onChange={e=>setActual(e.target.value)} placeholder="0.00"/></label><article className={difference===null?"":Math.abs(difference)<.01?"matched":"different"}><small>הפרש</small><strong>{difference===null?"—":money(difference)}</strong>{difference!==null&&(Math.abs(difference)<.01?<span><CheckCircle2/> תואם</span>:<span><TriangleAlert/> דורש בירור</span>)}</article></div><label>הערה לבדיקה<input value={note} onChange={e=>setNote(e.target.value)} placeholder="לא חובה"/></label><div className="reconciliation-actions"><Button disabled={busy||actual===""} onClick={()=>void save()}><Save/>{busy?"שומר...":"שמירת בדיקה"}</Button><Button variant="outline" disabled={busy} onClick={()=>void recordReturn()}><RotateCcw/>רישום החזרת הוראת קבע</Button></div>{notice&&<p className="reconciliation-notice">{notice}</p>}{!!data?.history.length&&<div className="reconciliation-history"><h3>בדיקות אחרונות</h3>{data.history.map(row=><article key={row.id}><span>{row.matched?<CheckCircle2/>:<TriangleAlert/>}<b>{row.date}</b></span><span>מערכת {money(row.expectedBalance)}</span><span>בנק {money(row.actualBalance)}</span><strong className={row.matched?"matched":"different"}>{row.matched?"תואם":`הפרש ${money(row.difference)}`}</strong></article>)}</div>}</section>
}
