"use client";
import { useEffect, useState } from "react";
import { Check, CheckCircle2, Landmark, LockKeyhole, Save, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { todayInIsrael } from "./settlement";
type Row={id:number;date:string;expectedBalance:number;actualBalance:number;difference:number;matched:boolean};
type Data={expectedBalance:number;baseline:{date:string;balance:number}|null;history:Row[]};
const money=(n:number)=>Number(n||0).toLocaleString("he-IL",{style:"currency",currency:"ILS"});
export default function BankReconciliation(){
 const[allowed,setAllowed]=useState<boolean|null>(null),[date,setDate]=useState(todayInIsrael()),[data,setData]=useState<Data|null>(null),[actual,setActual]=useState(""),[note,setNote]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([fetch("/api/me").then(r=>r.json()),fetch("/api/settings").then(r=>r.json())]).then(([me,settings])=>{let users:Array<{email:string;role:string;status:string}>=[];try{users=JSON.parse(settings.settings?.access_users||"[]")}catch{}setAllowed(users.some(x=>x.email?.toLowerCase()===me.user?.email?.toLowerCase()&&x.role==="admin"&&x.status==="active"))}).catch(()=>setAllowed(false))},[]);
 const load=async()=>{const r=await fetch(`/api/bank-reconciliation?date=${date}&currency=ILS`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)};
 useEffect(()=>{if(!allowed)return;setNotice("");void load().catch(()=>setNotice("לא ניתן לחשב את היתרה כרגע"))},[date,allowed]);
 if(allowed!==true)return null;
 const difference=actual===""?null:Math.round((Number(actual)-Number(data?.expectedBalance||0))*100)/100,matched=difference!==null&&Math.abs(difference)<.01;
 async function save(){setBusy(true);setNotice("");try{const r=await fetch("/api/bank-reconciliation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,currency:"ILS",actualBalance:actual,note})}),j=await r.json();if(!r.ok)throw new Error(j.error);setNotice(j.reconciliation.matched?"הבדיקה נשמרה — היתרה תואמת":"הבדיקה נשמרה — נמצא הפרש לבדיקה");setActual("");setNote("");await load()}catch(e){setNotice(e instanceof Error?e.message:"השמירה נכשלה")}finally{setBusy(false)}}
 return <section className="bank-reconciliation"><header><span className="reconciliation-icon"><Landmark/></span><div><small><LockKeyhole/> למנהל המערכת בלבד</small><h3>בקרת יתרת הבנק</h3><p>השוואה קצרה בין היתרה הצפויה במערכת ליתרה שמופיעה בבנק.</p></div>{data?.history[0]?.matched&&<em><Check/> נבדק לאחרונה</em>}</header><div className="reconciliation-workspace"><div className="reconciliation-expected"><span>לפי המערכת, נכון לתאריך</span><label><input type="date" max={todayInIsrael()} value={date} onChange={e=>setDate(e.target.value)}/></label><strong>{data?money(data.expectedBalance):"מחשב…"}</strong><small>{data?.baseline?`מבוסס על אימות מ־${data.baseline.date}`:"זו בדיקת הפתיחה הראשונה"}</small></div><div className="reconciliation-check"><label><span>מה היתרה שמופיעה בבנק?</span><div className="balance-input"><b>₪</b><input aria-label="יתרה בפועל בבנק" inputMode="decimal" type="number" step="0.01" value={actual} onChange={e=>setActual(e.target.value)} placeholder="0.00"/></div></label><div className={`reconciliation-result ${difference===null?"idle":matched?"matched":"different"}`}>{difference===null?<><Landmark/><span>הזינו את היתרה לבדיקה</span></>:matched?<><CheckCircle2/><span><b>הסכומים תואמים</b><small>אין הפרש</small></span></>:<><TriangleAlert/><span><b>נמצא הפרש של {money(difference)}</b><small>מומלץ לבדוק תנועות שטרם נקלטו</small></span></>}</div><label className="reconciliation-note"><span>הערה <small>לא חובה</small></span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="למשל: נבדק מול האפליקציה של הבנק"/></label><Button disabled={busy||actual===""} onClick={()=>void save()}><Save/>{busy?"שומר…":"שמירת הבדיקה"}</Button></div></div>{notice&&<p className="reconciliation-notice">{notice}</p>}{!!data?.history.length&&<details className="reconciliation-history"><summary>היסטוריית בדיקות <span>{data.history.length}</span></summary><div>{data.history.map(row=><article key={row.id}><span className={row.matched?"matched":"different"}>{row.matched?<CheckCircle2/>:<TriangleAlert/>}</span><b>{row.date}</b><small>מערכת {money(row.expectedBalance)}</small><small>בנק {money(row.actualBalance)}</small><strong className={row.matched?"matched":"different"}>{row.matched?"תואם":money(row.difference)}</strong></article>)}</div></details>}</section>
}
