"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { CalendarClock,Check,ChevronDown,ExternalLink,Filter,Phone,Search,Target,UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { defaultRelationshipGroups,relationshipStatuses } from "./relationship-config";
import { formatHebrewDate } from "./hebrew-date";

type Person={id:number;fullName:string;phone:string;email:string};
type Group={key:string;label:string;rank:number|null;source:"automatic"|"manual";count?:number};
type Item={id:number;cardName:string;people:Person[];phone:string;relationshipGroups:string[];manualRelationshipGroups:string[];automaticRelationshipGroups:string[];priorityRank:number;priorityScore:number;relationshipStatus:string;relationshipNotes:string;relationshipHandledBy:string;nextAction:string;nextContactDate:string|null;lastDonationDate:string|null;periodTotal:number;recurringStatus:string;recurringAmount:number;eligibleForRecurringIncrease:boolean;campaigns:Array<{id:number;name:string}>};
type Payload={items:Item[];total:number;summary:Group[];config:Group[];campaigns:Array<{id:number;name:string}>};
const money=(value:number)=>Number(value||0).toLocaleString("he-IL",{style:"currency",currency:"ILS",maximumFractionDigits:0});
const statusLabel=(value:string)=>relationshipStatuses.find(x=>x[0]===value)?.[1]||value;
const civil=(value:string)=>new Intl.DateTimeFormat("he-IL").format(new Date(`${value}T12:00:00`));

export default function RetentionCenter(){
 const[items,setItems]=useState<Item[]>([]),[summary,setSummary]=useState<Group[]>(defaultRelationshipGroups),[config,setConfig]=useState<Group[]>(defaultRelationshipGroups),[campaigns,setCampaigns]=useState<Array<{id:number;name:string}>>([]),[total,setTotal]=useState(0),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(""),[group,setGroup]=useState(""),[status,setStatus]=useState(""),[campaign,setCampaign]=useState(""),[sort,setSort]=useState("priority"),[recent,setRecent]=useState("365"),[page,setPage]=useState(1),[editing,setEditing]=useState<Item|null>(null),[logging,setLogging]=useState<Item|null>(null),[notice,setNotice]=useState("");
 const groupMap=useMemo(()=>new Map(config.map(x=>[x.key,x])),[config]);
 async function load(){setLoaded(false);const params=new URLSearchParams({page:String(page),limit:"30",q:query,group,status,campaign,sort,recent});const response=await fetch(`/api/retention?${params}`,{cache:"no-store"});if(response.ok){const data=await response.json() as Payload;setItems(data.items);setTotal(data.total);setSummary(data.summary);setConfig(data.config);setCampaigns(data.campaigns)}setLoaded(true)}
 useEffect(()=>{const timer=setTimeout(()=>void load(),query?250:0);return()=>clearTimeout(timer)},[query,group,status,campaign,sort,recent,page]);
 useEffect(()=>setPage(1),[query,group,status,campaign,sort,recent]);
 async function update(id:number,patch:Record<string,unknown>,message:string){const response=await fetch("/api/retention",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(response.ok){setNotice(message);setEditing(null);await load()}else setNotice("לא ניתן לשמור את השינוי")}
 return <div className="retention-page" dir="rtl"><header className="retention-header"><div><span className="eyebrow">CRM · רשימת עבודה</span><h1>שימור קשר</h1><p>רשימת תורמים לפי עדיפות לפנייה, חידוש, הגדלה וטיפוח</p></div><div className="retention-total"><Target/><span><b>{total}</b><small>כרטיסים לפעולה</small></span></div></header>
 {notice&&<div className="save-notice"><Check/>{notice}</div>}
 <section className="retention-summary" aria-label="סיכום דרגות עדיפות">{summary.filter(x=>x.rank!==null).map(item=><button key={item.key} className={group===item.key?"active":""} onClick={()=>setGroup(group===item.key?"":item.key)}><span>#{item.rank}</span><b>{item.label}</b><em>{item.count||0}</em></button>)}</section>
 <section className="retention-toolbar"><label className="retention-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש לפי שם, טלפון או דוא״ל"/></label><div className="retention-filters"><label><Filter/><select aria-label="קבוצת עדיפות" value={group} onChange={e=>setGroup(e.target.value)}><option value="">כל קבוצות העדיפות</option>{config.map(x=><option value={x.key} key={x.key}>{x.rank?`#${x.rank} `:""}{x.label}</option>)}</select></label><select aria-label="סטטוס טיפול" value={status} onChange={e=>setStatus(e.target.value)}><option value="">כל סטטוסי הטיפול</option>{relationshipStatuses.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select><select aria-label="קמפיין" value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">כל הקמפיינים</option>{campaigns.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select aria-label="מיון" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">עדיפות מומלצת</option><option value="followup">מועד follow-up</option><option value="recent">תרומה אחרונה</option><option value="donations">סכום תרומות</option></select>{group==="recent_donor"&&<select aria-label="טווח תרומות אחרונות" value={recent} onChange={e=>setRecent(e.target.value)}><option value="30">30 ימים</option><option value="90">90 ימים</option><option value="180">חצי שנה</option><option value="365">שנה</option><option value="all">כל ההיסטוריה</option></select>}</div></section>
 {!loaded?<div className="retention-skeleton">{[1,2,3].map(x=><i key={x}/>)}</div>:items.length?<section className="retention-list">{items.map(item=><article className="retention-row" key={item.id}><div className="retention-primary"><div className="rank-badge"><b>#{item.priorityRank===99?"—":item.priorityRank}</b><small>עדיפות</small></div><div className="retention-identity"><Link href={`/donors/${item.id}?origin=retention&return=${encodeURIComponent('/?view=retention')}`}>{item.cardName}<ExternalLink/></Link><p>{item.people.map(person=>person.fullName).join(" · ")||"כרטיס ללא פרטי אדם"}</p><div className="group-chips">{item.relationshipGroups.map(key=>{const meta=groupMap.get(key);return <span key={key} className={item.automaticRelationshipGroups.includes(key)?"automatic":"manual"}>{meta?.rank?`#${meta.rank} `:""}{meta?.label||key}<small>{item.automaticRelationshipGroups.includes(key)?"אוטומטי":"ידני"}</small></span>})}</div></div></div><div className="retention-data"><div><small>תרומה אחרונה</small><b>{item.lastDonationDate?formatHebrewDate(item.lastDonationDate):"אין תרומות"}</b>{item.lastDonationDate&&<em>{civil(item.lastDonationDate)}</em>}</div><div><small>תרומות ב־12 חודשים</small><b>{money(item.periodTotal)}</b></div><div><small>הוראת קבע</small><b>{item.recurringStatus==="active"?`${money(item.recurringAmount)} פעילה`:item.recurringStatus==="ended"?"הסתיימה":"ללא הו״ק"}</b></div><div><small>פעולה הבאה</small><b>{item.nextAction||"טרם נקבעה"}</b>{item.nextContactDate&&<em>{civil(item.nextContactDate)}</em>}</div><div><small>סטטוס טיפול</small><b className={`relationship-status status-${item.relationshipStatus}`}>{statusLabel(item.relationshipStatus)}</b></div></div><details className="retention-mobile-more"><summary>מידע נוסף <ChevronDown/></summary><p>טלפון: {item.phone||"לא הוזן"}</p><p>מטפל: {item.relationshipHandledBy||"לא הוגדר"}</p>{item.relationshipNotes&&<p>{item.relationshipNotes}</p>}</details><div className="retention-actions"><Button variant="outline" asChild><Link href={`/donors/${item.id}?origin=retention&return=${encodeURIComponent('/?view=retention')}`}><UsersRound/>פתיחת כרטיס</Link></Button><Button variant="outline" onClick={()=>setLogging(item)}><Phone/>תיעוד שיחה</Button><Button variant="outline" onClick={()=>setEditing(item)}><CalendarClock/>עדכון טיפול</Button><Button onClick={()=>void update(item.id,{relationshipStatus:"handled"},"הכרטיס סומן כטופל")}><Check/>סימון טופל</Button></div></article>)}</section>:<div className="database-empty"><UsersRound/><h3>אין כרטיסים שמתאימים לסינון</h3><p>אפשר לשנות את המסננים או להוסיף קבוצות שימור מתוך כרטיס התורם.</p></div>}
 {total>30&&<nav className="retention-pagination" aria-label="עמודי שימור"><Button variant="outline" disabled={page===1} onClick={()=>setPage(x=>x-1)}>הקודם</Button><span>עמוד {page} מתוך {Math.ceil(total/30)}</span><Button variant="outline" disabled={page>=Math.ceil(total/30)} onClick={()=>setPage(x=>x+1)}>הבא</Button></nav>}
 <RelationshipDialog item={editing} config={config} onClose={()=>setEditing(null)} onSave={(patch)=>editing&&void update(editing.id,patch,"פרטי השימור עודכנו")}/><LogDialog item={logging} onClose={()=>setLogging(null)} onSaved={async()=>{setLogging(null);setNotice("השיחה נוספה להיסטוריית הקשר");await load()}}/></div>
}

function RelationshipDialog({item,config,onClose,onSave}:{item:Item|null;config:Group[];onClose:()=>void;onSave:(patch:Record<string,unknown>)=>void}){const manual=config.filter(x=>x.source==="manual");const[groups,setGroups]=useState<string[]>([]),[status,setStatus]=useState("needs_contact"),[action,setAction]=useState(""),[date,setDate]=useState(""),[notes,setNotes]=useState(""),[handledBy,setHandledBy]=useState(""),[increase,setIncrease]=useState(false);useEffect(()=>{if(item){setGroups(item.manualRelationshipGroups);setStatus(item.relationshipStatus);setAction(item.nextAction);setDate(item.nextContactDate||"");setNotes(item.relationshipNotes||"");setHandledBy(item.relationshipHandledBy||"");setIncrease(item.eligibleForRecurringIncrease)}},[item]);return <Dialog open={!!item} onOpenChange={open=>!open&&onClose()}><DialogContent dir="rtl" className="relationship-dialog"><DialogHeader className="text-right"><DialogTitle>עדכון שימור וקשר · {item?.cardName}</DialogTitle></DialogHeader><div className="automatic-groups"><b>שיוכים אוטומטיים</b><div className="group-chips">{item?.automaticRelationshipGroups.map(key=><span className="automatic" key={key}>{config.find(x=>x.key===key)?.label}<small>קריאה בלבד</small></span>)}</div></div><fieldset><legend>קבוצות ידניות</legend><div className="relationship-checks">{manual.map(group=><label key={group.key}><input type="checkbox" checked={groups.includes(group.key)} onChange={e=>setGroups(value=>e.target.checked?[...value,group.key]:value.filter(x=>x!==group.key))}/><span>{group.label}</span></label>)}</div></fieldset><div className="detail-form-grid"><label><span>סטטוס טיפול</span><select value={status} onChange={e=>setStatus(e.target.value)}>{relationshipStatuses.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label><label><span>פעולה הבאה</span><input value={action} onChange={e=>setAction(e.target.value)} placeholder="לדוגמה: להתקשר בנוגע לחידוש"/></label><label><span>תאריך לפעולה הבאה</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>מי מטפל</span><input value={handledBy} onChange={e=>setHandledBy(e.target.value)}/></label><label className="wide"><span>הערה קצרה</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><label className="increase-toggle"><input type="checkbox" checked={increase} onChange={e=>setIncrease(e.target.checked)}/><span><b>מתאים לבקשת הגדלת הו״ק</b><small>יוסיף שיוך אוטומטי לקבוצת הגדלת סכום הו״ק כאשר קיימת הו״ק פעילה.</small></span></label><div className="dialog-actions"><Button variant="outline" onClick={onClose}>ביטול</Button><Button onClick={()=>onSave({manualRelationshipGroups:groups,relationshipStatus:status,nextAction:action,nextFollowUpDate:date||null,relationshipNotes:notes,relationshipHandledBy:handledBy,eligibleForRecurringIncrease:increase})}>שמירת השינויים</Button></div></DialogContent></Dialog>}

function LogDialog({item,onClose,onSaved}:{item:Item|null;onClose:()=>void;onSaved:()=>void}){const[summary,setSummary]=useState(""),[outcome,setOutcome]=useState(""),[followUp,setFollowUp]=useState(""),[busy,setBusy]=useState(false);async function save(){if(!item||!summary.trim())return;setBusy(true);const response=await fetch(`/api/donors/${item.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"שיחת טלפון",summary,outcome,followUpDate:followUp||null,occurredAt:new Date().toISOString()})});if(response.ok){if(followUp)await fetch("/api/retention",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,relationshipStatus:"follow_up",nextAction:outcome||"שיחת המשך",nextFollowUpDate:followUp})});setSummary("");setOutcome("");setFollowUp("");onSaved()}setBusy(false)}return <Dialog open={!!item} onOpenChange={open=>!open&&onClose()}><DialogContent dir="rtl" className="relationship-dialog"><DialogHeader className="text-right"><DialogTitle>תיעוד שיחה · {item?.cardName}</DialogTitle></DialogHeader><div className="detail-form-grid"><label className="wide"><span>סיכום השיחה *</span><textarea rows={4} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label><span>תוצאה / פעולה הבאה</span><input value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label><span>תאריך follow-up</span><input type="date" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label></div><div className="dialog-actions"><Button variant="outline" onClick={onClose}>ביטול</Button><Button disabled={busy||!summary.trim()} onClick={()=>void save()}>{busy?"שומר...":"שמירת השיחה"}</Button></div></DialogContent></Dialog>}
