"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Plus, Save, Trash2 } from "lucide-react";
import { rulesFromSettings, type SettlementRule } from "./settlement";
const modes={same:"באותו יום",days:"מספר ימים לאחר העסקה",monthly:"יום קבוע בחודש (המועד הבא)",next_month:"יום קבוע בחודש הבא",manual:"תאריך ידני"};
export default function SettlementSettings(){
 const[rules,setRules]=useState<SettlementRule[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{fetch("/api/settings").then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setRules(rulesFromSettings(d.settings));setLoaded(true)}).catch(()=>setNotice("לא ניתן לטעון את מועדי הזיכוי"))},[]);
 async function save(){setBusy(true);try{if(rules.some(r=>!r.method.trim()||!Number.isInteger(r.day)||r.day<0||((r.mode==="monthly"||r.mode==="next_month")&&(r.day<1||r.day>31))))throw Error();if(new Set(rules.map(r=>r.method.trim())).size!==rules.length)throw Error();const r=await fetch("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({settlement_rules:JSON.stringify(rules)})});if(!r.ok)throw Error();setNotice("הכללים נשמרו. התחזית מתעדכנת גם לתנועות קיימות ללא מועד ידני; אישורי זיכוי נשמרים.");window.dispatchEvent(new Event("settlement-updated"));}catch{setNotice("בדוק את שמות האמצעים ואת מספר הימים ונסה שוב.")}finally{setBusy(false)}}
 return <section className="config-panel settlement-settings"><div className="panel-head"><div><h2>מועדי זיכוי</h2><p>ניהול מועד הכניסה הצפוי לבנק לכל אמצעי תשלום.</p></div><Button disabled={!loaded||busy} onClick={save}><Save/>{busy?"שומר…":"שמירת כללים"}</Button></div><div className="bank-stack">{notice&&<p className="settings-status" role="status">{notice}</p>}{rules.map((r,i)=><article className="bank-rule" key={i}><div className="bank-rule-title"><b>{r.method||"אמצעי תשלום חדש"}</b><button className="danger-action" aria-label={`מחיקת ${r.method||"הכלל"}`} onClick={()=>{if(window.confirm("למחוק את כלל הזיכוי הזה?"))setRules(old=>old.filter((_,j)=>j!==i))}}><Trash2/></button></div><label><span>אמצעי תשלום</span><input value={r.method} onChange={e=>setRules(old=>old.map((v,j)=>j===i?{...v,method:e.target.value}:v))}/></label><label><span>מועד הזיכוי</span><select value={r.mode} onChange={e=>setRules(old=>old.map((v,j)=>j===i?{...v,mode:e.target.value as SettlementRule["mode"],day:Math.max(1,v.day)}:v))}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{!["same","manual"].includes(r.mode)&&<label><span>{r.mode==="days"?"מספר ימים":"יום בחודש"}</span><input type="number" min={r.mode==="days"?0:1} max={r.mode==="days"?365:31} value={r.day} onChange={e=>setRules(old=>old.map((v,j)=>j===i?{...v,day:Number(e.target.value)}:v))}/></label>}</article>)}<Button className="settings-add-wide" variant="outline" disabled={!loaded} onClick={()=>setRules(r=>[...r,{method:"",mode:"manual",day:1}])}><Plus/>הוספת אמצעי תשלום</Button><p className="settings-help">הכלל חל על תנועה חד־פעמית או הוראת קבע. בחודש קצר, יום 29–31 מותאם ליום האחרון בחודש.</p></div></section>
}
