"use client";
import { useEffect, useState } from "react";
import { Check, Save, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
type Settings=Record<string,string>;
type Section="general"|"finance"|"automation";
const defaults:Settings={organization_name:"בית חב״ד לב העיר בית שמש",manager_name:"שניאור זלמן",organization_phone:"",organization_email:"",organization_address:"",organization_number:"",default_delivery:"WhatsApp",default_currency:"ILS",receipt_prefix:"",credit_fee:"1.2",bit_fee:"0",bank_fee:"0",bank_recurring_setup_fee:"8.6",bank_recurring_charge_fee:"1.7",bank_recurring_return_fee:"22.2",vat_rate:"18",failed_recurring_task:"true",ended_recurring_task:"true",unmatched_movement_task:"true",special_date_reminder:"true",backup_reminder:"weekly"};
const Field=({label,k,value,set,type="text",options,hint}:{label:string;k:string;value:string;set:(k:string,v:string)=>void;type?:string;options?:[string,string][];hint?:string})=><label><span>{label}</span>{options?<select value={value} onChange={e=>set(k,e.target.value)}>{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>:<input type={type} value={value} onChange={e=>set(k,e.target.value)}/>} {hint&&<small>{hint}</small>}</label>;
function Toggle({label,detail,k,value,set}:{label:string;detail:string;k:string;value:string;set:(k:string,v:string)=>void}){const on=value==="true";return <button type="button" className="settings-toggle" onClick={()=>set(k,on?"false":"true")} aria-pressed={on}><span className={on?"on":""}><i/></span><div><b>{label}</b><small>{detail}</small></div></button>}
export default function SettingsCenter({section="general"}:{section?:Section}){
 const[s,setS]=useState<Settings>(defaults),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(j=>setS(v=>({...v,...j.settings}))).catch(()=>setNotice("לא ניתן לטעון את ההגדרות השמורות"))},[]);
 const set=(k:string,v:string)=>setS(x=>({...x,[k]:v}));
 async function save(keys:string[]){setBusy(true);setNotice("");try{const payload=Object.fromEntries(keys.map(k=>[k,k==="bank_fee"?"0":s[k]??""]));const r=await fetch("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"לא ניתן לשמור");setNotice("השינויים נשמרו")}catch(e){setNotice(e instanceof Error?e.message:"לא ניתן לשמור את ההגדרות")}finally{setBusy(false)}}
 if(section==="general")return <div className="settings-complete settings-general">{notice&&<div className="save-notice"><Check/>{notice}</div>}<section className="config-panel"><div className="panel-head"><div><h2>פרטי בית חב״ד</h2><p>המידע שיופיע במסמכים, בדוחות ובהודעות.</p></div><Button disabled={busy} onClick={()=>save(["organization_name","manager_name","organization_phone","organization_email","organization_address","organization_number","receipt_prefix"])}><Save/>{busy?"שומר…":"שמירה"}</Button></div><div className="config-grid general"><Field label="שם המוסד" k="organization_name" value={s.organization_name} set={set}/><Field label="מנהל המערכת" k="manager_name" value={s.manager_name} set={set}/><Field label="טלפון" k="organization_phone" value={s.organization_phone} set={set}/><Field label="דוא״ל" k="organization_email" value={s.organization_email} set={set} type="email"/><Field label="כתובת" k="organization_address" value={s.organization_address} set={set}/><Field label="מספר עמותה / מוסד" k="organization_number" value={s.organization_number} set={set}/><Field label="קידומת מסמכים" k="receipt_prefix" value={s.receipt_prefix} set={set}/></div></section><section className="config-panel"><div className="panel-head"><div><h2>ברירות מחדל</h2><p>העדפות קבועות להזנת מידע חדש.</p></div><Button disabled={busy} onClick={()=>save(["default_delivery","default_currency"])}><Save/>שמירה</Button></div><div className="config-grid compact"><Field label="דרך משלוח מועדפת" k="default_delivery" value={s.default_delivery} set={set} options={[["WhatsApp","WhatsApp"],["email","דוא״ל"],["mail","דואר"],["none","לא לשלוח"]]}/><Field label="מטבע ברירת מחדל" k="default_currency" value={s.default_currency} set={set} options={[["ILS","שקל חדש (₪)"],["USD","דולר ($)"],["EUR","אירו (€)"]]}/></div></section></div>;
 if(section==="finance")return <div className="settings-complete">{notice&&<div className="save-notice"><Check/>{notice}</div>}<section className="config-panel fee-settings"><div className="panel-head"><div><h2>עמלות תשלום</h2><p>העמלות מנוכות אוטומטית לצורך חישוב הנטו.</p></div><Button disabled={busy} onClick={()=>save(["credit_fee","bit_fee","bank_fee","bank_recurring_setup_fee","bank_recurring_charge_fee","bank_recurring_return_fee","vat_rate"])}><Save/>{busy?"שומר…":"שמירת עמלות"}</Button></div><div className="fee-free-note"><ShieldCheck/><div><b>העברה בנקאית רגילה — ללא עמלה</b><small>המערכת תמיד מחשבת העברה רגילה במלואה.</small></div></div><div className="config-grid"><Field label="עמלת אשראי (%)" k="credit_fee" value={s.credit_fee} set={set} type="number"/><Field label="עמלת Bit (%)" k="bit_fee" value={s.bit_fee} set={set} type="number"/><Field label="מע״מ (%)" k="vat_rate" value={s.vat_rate} set={set} type="number"/><Field label="הקמת הוראת קבע בנקאית" k="bank_recurring_setup_fee" value={s.bank_recurring_setup_fee} set={set} type="number" hint="₪ לפני מע״מ, לכל הוראה"/><Field label="חיוב הוראת קבע בנקאית" k="bank_recurring_charge_fee" value={s.bank_recurring_charge_fee} set={set} type="number" hint="₪ לפני מע״מ, לכל שידור"/><Field label="החזרת הוראת קבע בנקאית" k="bank_recurring_return_fee" value={s.bank_recurring_return_fee} set={set} type="number" hint="₪ לפני מע״מ, לכל החזרה"/></div></section></div>;
 return <div className="settings-complete">{notice&&<div className="save-notice"><Check/>{notice}</div>}<section className="config-panel"><div className="panel-head"><div><h2>התראות ומשימות אוטומטיות</h2><p>בחרו רק את האירועים שדורשים פעולה מהצוות.</p></div><Button disabled={busy} onClick={()=>save(["failed_recurring_task","ended_recurring_task","unmatched_movement_task","special_date_reminder","backup_reminder"])}><Save/>{busy?"שומר…":"שמירה"}</Button></div><div className="toggle-list"><Toggle label="חיוב קבוע שנכשל" detail="פתיחת משימת טיפול מיידית" k="failed_recurring_task" value={s.failed_recurring_task} set={set}/><Toggle label="הוראת קבע שהסתיימה" detail="פתיחת משימת חידוש קשר" k="ended_recurring_task" value={s.ended_recurring_task} set={set}/><Toggle label="תנועה שלא שויכה" detail="העברה לבדיקה אנושית" k="unmatched_movement_task" value={s.unmatched_movement_task} set={set}/><Toggle label="תאריך מיוחד מתקרב" detail="יצירת תזכורת לצוות" k="special_date_reminder" value={s.special_date_reminder} set={set}/><Field label="תזכורת לגיבוי" k="backup_reminder" value={s.backup_reminder} set={set} options={[["weekly","אחת לשבוע"],["monthly","אחת לחודש"],["none","ללא תזכורת"]]}/></div></section></div>;
}
